## Model VGG19: FLOPs & Parameters


#### 0. 1 cuda is available

In [1]:
import torch

USE_CUDA = torch.cuda.is_available()
USE_CUDA

True

#### 0.2 pytorch version

In [2]:
import torch

torch.__version__

'1.8.1+cu102'

### 1. Pretrained VGG19 Model with Batch Normalization

In [47]:
import torchvision.models as models

model = models.vgg19_bn(pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.9.0', 'vgg19_bn', pretrained=True)

model.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): ReLU(inplace=True)
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): ReLU(inplace=True)
    (13): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (14): Conv2d(128, 256

#### 1.1 VGG19 Weight

In [4]:
model.features[1]

BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

In [5]:
model.features[1].weight.data.shape

torch.Size([64])

In [6]:
model.features[1].weight.data

tensor([ 1.5763e-07,  9.8841e-08,  2.4442e-01,  2.2678e-01,  2.4756e-01,
         5.9402e-07,  1.5344e-01,  5.5348e-01,  1.8775e-01,  4.0541e-08,
         7.3613e-08,  6.7899e-07,  1.9412e-08,  3.7765e-07, -1.5930e-07,
         4.6782e-01, -5.3255e-07,  1.8139e-02,  1.9039e-08,  2.0468e-07,
        -3.8896e-05,  8.2928e-07,  3.6763e-01, -5.7934e-08,  1.0634e-07,
         7.7692e-09, -1.2172e-07,  1.0209e-07,  1.0130e-07,  3.9670e-08,
         4.9515e-08,  6.8137e-07,  1.0767e-07,  6.3167e-08,  5.1813e-01,
         3.9662e-01,  4.0801e-06,  3.2676e-01,  3.0591e-08,  1.4233e-05,
        -4.0759e-07,  2.1676e-04,  1.8606e-06,  2.0022e-08,  6.8042e-07,
         1.0519e-06,  3.0301e-07,  1.7505e-08,  1.4339e-07,  2.6455e-08,
         3.7188e-01, -1.0622e-06,  1.9643e-01,  6.8300e-01,  1.8162e-01,
        -1.1994e-07,  3.4379e-01,  1.2878e-04,  6.3663e-01,  6.3070e-01,
         2.0438e-07,  1.0555e-08,  1.4975e-08,  3.4700e-06])

#### 1.2 VGG19 Convolution Layer

In [7]:
model.features[0]

Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [8]:
model.features[0].weight.data.shape

torch.Size([64, 3, 3, 3])

In [9]:
model.features[0].weight.data

tensor([[[[-3.2130e-08, -3.1717e-08, -6.7120e-08],
          [-2.9321e-08, -2.1596e-08, -5.3207e-08],
          [-5.3304e-08, -4.0832e-08, -6.6434e-08]],

         [[ 1.3710e-07,  1.2848e-07,  7.1270e-08],
          [ 1.5487e-07,  1.5186e-07,  8.3582e-08],
          [ 9.3392e-08,  9.9451e-08,  4.1284e-08]],

         [[ 1.7435e-07,  1.7840e-07,  1.0561e-07],
          [ 1.9644e-07,  1.9769e-07,  1.2560e-07],
          [ 1.1935e-07,  1.3447e-07,  5.9638e-08]]],


        [[[-6.3467e-08, -5.2714e-08, -3.8511e-08],
          [-1.4349e-08, -9.0426e-09, -1.7164e-08],
          [ 2.2282e-08,  1.9084e-08,  1.8150e-09]],

         [[-1.2191e-08, -6.1933e-09,  8.5022e-09],
          [ 3.8618e-08,  5.8869e-08,  2.2082e-08],
          [ 6.2501e-08,  7.0528e-08,  2.7185e-08]],

         [[ 3.0045e-08,  3.8003e-08,  3.5389e-08],
          [ 8.6743e-08,  1.1626e-07,  8.0502e-08],
          [ 7.9653e-08,  1.0057e-07,  6.7894e-08]]],


        [[[-1.3565e-01, -2.9960e-01, -1.5151e-01],
          [-2.6

### 2. Pretrained VGG19 Model without Batch Normalization

In [1]:
import torch
import torchvision.models as models

model = models.vgg19(pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.9.0', 'vgg19', pretrained=True)
model.eval()

Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to C:\Users\UPC/.cache\torch\hub\checkpoints\vgg19-dcbb9e9d.pth


  0%|          | 0.00/548M [00:00<?, ?B/s]

KeyboardInterrupt: 

### 2.1 features[0]: Conv2d

- 输入通道为RGB彩色图像三通道，输出通道为64，卷积核大小为3×3
- Conv2d weight：3个卷积核为一组，一共有64组卷积核，即 `model.features[0].weight.shape = [64, 3, 3, 3]`
- Conv2d bias：3个卷积核为一组，卷积核的结果相加，产生一个通道的结果。一共有64组，使用偏置对其调整，即 `model.features[0].bias.shape=[64]`

In [11]:
model.features[0]

Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [12]:
model.features[0].weight.shape

torch.Size([64, 3, 3, 3])

In [13]:
model.features[0].bias.shape

torch.Size([64])

### 2.2 features[2]: Conv2d 

- 输入通道为64，输出通道为64，卷积核大小为3×3
- Conv2d weight：64个3×3的卷积核为一组，一共有64组，即 `model.features[2].weight.shape=[64, 64, 3, 3]`
- Conv2d bias: 64个3×3的卷积核为一组，一共有64组，每一组内对应位置求和，即`model.features[2].bias.shape=[64]`

In [14]:
model.features[2]

Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [15]:
model.features[2].weight.shape

torch.Size([64, 64, 3, 3])

In [16]:
model.features[2].bias.shape

torch.Size([64])

### 2.3 Prune Conv2d Bias

In [22]:
bias = model.features[2].bias.clone()
mask = bias.gt(0.).float()
bias_mask = bias.mul(mask)
bias, mask, bias_mask

(tensor([-5.8394e-02, -1.4754e-01,  1.8017e-01, -2.8633e-01,  1.4053e-02,
         -3.9571e-02,  1.0259e-01, -8.8048e-04, -7.7598e-02, -1.8744e-01,
         -3.4763e-02,  2.2564e-02, -6.1512e-02, -3.9896e-01, -2.3920e-01,
          1.1534e-01, -1.1614e-01, -2.2889e-01, -1.6896e-01, -2.4117e-01,
          5.9063e-01,  4.4781e-04, -3.8955e-02, -8.2188e-01, -1.5366e-01,
          2.2464e-02,  4.2782e-01, -5.8604e-02, -4.8700e-02,  3.0054e-01,
         -5.6536e-02,  5.2338e-02,  2.4208e-01, -3.2136e-03,  4.8011e-01,
         -8.3752e-03,  1.7856e-01,  3.9528e-01, -2.2767e-02,  5.7821e-02,
          6.5798e-04, -1.3895e-01, -1.6600e-01,  7.9103e-03,  1.1497e-01,
          1.0045e-01,  2.3931e-01,  4.0163e-01, -1.3901e-01, -4.5015e-01,
          1.9804e-01, -1.4634e-01, -1.1509e-01,  7.2199e-02, -1.0609e-02,
          3.5647e-01,  9.0835e-02, -1.5250e-01,  2.1137e-01, -2.0729e-01,
          1.1017e-02,  2.3209e-01,  9.1408e-02,  2.5651e-02],
        grad_fn=<CloneBackward>),
 tensor([0., 0.,

### 2.4 Prune Conv2d Weight

In [26]:
weight = model.features[2].weight.clone()
num_channel = weight.shape[0]
mask = torch.randn(num_channel).gt(0.).float()
for i in range(num_channel):
    if mask[i] <= 0:
        weight[i] = torch.zeros()

torch.Size([64, 64, 3, 3])


tensor([1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
        0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 0., 0., 0., 0., 1., 0., 0., 1.])

### 3. Handle Model 

In [9]:
import math
import torch
import torch.nn as nn
from torch.autograd import Variable

__all__ = ['vgg']

defaultcfg = {
    11: [64, 'M', 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512],
    13: [64, 64, 'M', 128, 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512],
    16: [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512],
    19: [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 256, 'M', 512, 512, 512, 512, 'M', 512, 512, 512, 512],
}


class vgg(nn.Module):
    def __init__(self, dataset='cifar10', depth=19, init_weights=True, cfg=None, batch_norm=True, conv_cfg=None):
        super(vgg, self).__init__()

        self.conv_cfg = conv_cfg
        if cfg is None:
            cfg = defaultcfg[depth]

        self.feature = self.make_layers(cfg, batch_norm)

        num_classes = 10
        if dataset == 'cifar100':
            num_classes = 100
        self.classifier = nn.Linear(cfg[-1], num_classes)

        if init_weights:
            self._initialize_weights()

    def make_layers(self, cfg, batch_norm=False):
        layers = []
        in_channels = 3
        for v in cfg:
            if v == 'M':
                layers += [nn.MaxPool2d(kernel_size=2, stride=2)]
            else:
                conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=1, bias=False)
                if batch_norm:
                    layers += [conv2d, nn.BatchNorm2d(v), nn.ReLU(inplace=True)]
                else:
                    layers += [conv2d, nn.ReLU(inplace=True)]
                in_channels = v
        return nn.Sequential(*layers)

    def forward(self, x):
        conv_value = []
        if self.conv_cfg:
            conv_idx = 0
            for k, m in enumerate(self.feature):
                x = m(x)
                if isinstance(m, nn.Conv2d):
                    conv_idx += 1
                    if conv_idx in self.conv_cfg:
                        conv_value.append(x)
        else:
            x = self.feature(x)

        x = nn.AvgPool2d(2)(x)
        x = x.view(x.size(0), -1)
        y = self.classifier(x)

        if len(conv_value):
            return y, conv_value
        else:
            return y

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
                if m.bias is not None:
                    m.bias.data.zero_()
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(0.5)
                m.bias.data.zero_()
            elif isinstance(m, nn.Linear):
                m.weight.data.normal_(0, 0.01)
                m.bias.data.zero_()


model = vgg(dataset='cifar10', depth=19)
model.eval()
# model

vgg(
  (feature): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (8): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): ReLU(inplace=True)
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (11): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): ReLU(inplace=True)
    (13): MaxPool2d(kernel_size=2, stride=2, padding=0, dilatio

### 4.  Pytorch统计FLOPs和Parameters

#### 4.1 thop
    `input` 与 `model` 需要位于同一device，比如 model.cuda() 和 input.cuda()

In [3]:
import torch
from thop import profile
from thop import clever_format

input = torch.randn(1, 3, 32, 32)
flops, params = profile(model, inputs=(input, ))
flops, params

[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register count_bn() for <class 'torch.nn.modules.batchnorm.BatchNorm2d'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.activation.ReLU'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.pooling.MaxPool2d'>.
[WARN] Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.
[INFO] Register count_linear() for <class 'torch.nn.modules.linear.Linear'>.
[WARN] Cannot find rule for <class '__main__.vgg'>. Treat it as zero Macs and zero Params.


G:\Anaconda3\envs\python37\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


(398742528.0, 20035018.0)

In [4]:
flops, params = clever_format([flops, params], "%.2f")
flops, params

('398.74M', '20.04M')

#### 4.2 torchstat

In [6]:
from torchstat import stat

stat(model, (3, 32, 32))

      module name  input shape output shape      params memory(MB)           MAdd          Flops  MemRead(B)  MemWrite(B) duration[%]   MemR+W(B)
0       feature.0    3  32  32   64  32  32      1728.0       0.25    3,473,408.0    1,769,472.0     19200.0     262144.0       0.00%    281344.0
1       feature.1   64  32  32   64  32  32       128.0       0.25      262,144.0      131,072.0    262656.0     262144.0       0.00%    524800.0
2       feature.2   64  32  32   64  32  32         0.0       0.25       65,536.0       65,536.0    262144.0     262144.0       0.00%    524288.0
3       feature.3   64  32  32   64  32  32     36864.0       0.25   75,431,936.0   37,748,736.0    409600.0     262144.0      33.33%    671744.0
4       feature.4   64  32  32   64  32  32       128.0       0.25      262,144.0      131,072.0    262656.0     262144.0       0.00%    524800.0
5       feature.5   64  32  32   64  32  32         0.0       0.25       65,536.0       65,536.0    262144.0     262144.0   

#### 4.3  ptflops

In [7]:
import torchvision.models as models
import torch
from ptflops import get_model_complexity_info

with torch.cuda.device(0):
    macs, params = get_model_complexity_info(model, (3, 32, 32), as_strings=True,
                                           print_per_layer_stat=True, verbose=True)
print('{:<30}  {:<8}'.format('Computational complexity: ', macs))
print('{:<30}  {:<8}'.format('Number of parameters: ', params))
macs, params

vgg(
  20.035 M, 100.000% Params, 0.399 GMac, 100.000% MACs, 
  (feature): Sequential(
    20.03 M, 99.974% Params, 0.399 GMac, 99.999% MACs, 
    (0): Conv2d(0.002 M, 0.009% Params, 0.002 GMac, 0.443% MACs, 3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (1): BatchNorm2d(0.0 M, 0.001% Params, 0.0 GMac, 0.033% MACs, 64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(0.0 M, 0.000% Params, 0.0 GMac, 0.016% MACs, inplace=True)
    (3): Conv2d(0.037 M, 0.184% Params, 0.038 GMac, 9.457% MACs, 64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (4): BatchNorm2d(0.0 M, 0.001% Params, 0.0 GMac, 0.033% MACs, 64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(0.0 M, 0.000% Params, 0.0 GMac, 0.016% MACs, inplace=True)
    (6): MaxPool2d(0.0 M, 0.000% Params, 0.0 GMac, 0.016% MACs, kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (7): Conv2d(0.074 M, 0.368% Params, 0.0

('0.4 GMac', '20.04 M')

### 5. Pruned Model

In [2]:
import os
import torch

def resume_model(resume_file):
    if not os.path.isfile(resume_file):
        raise ValueError("Resume model file is not found at '{}'".format(resume_file))
    print("=> loading checkpoint '{}'".format(resume_file))
    checkpoint = torch.load(resume_file)
    start_epoch = checkpoint['epoch']
    best_prec1 = checkpoint['best_prec1']
    state_dict = checkpoint['state_dict']
    opti_dict = checkpoint['optimizer']
    if 'cfg' in checkpoint:
        cfg = checkpoint['cfg']
    else:
        cfg = None
    print("cfg: {}".format(cfg))
    print("=> loaded checkpoint '{}' (epoch {}) Prec1: {:f}"
          .format(resume_file, start_epoch, best_prec1))
    return state_dict, opti_dict, start_epoch, best_prec1, cfg

In [8]:
filepath = r"G:\lizulin\network-slimming\logs\ft_inherit_bn_prune_vgg19_cifar10_percent_0.7_seed_2\model_best.pth.tar"
filepath2 = r"D:\Project\Pycharm\network-slimming\logs\attention_fine_tune_feature_vgg19_percent_0.7\model_best.pth.tar"
filepath3 = r"D:\Project\Pycharm\network-slimming\logs\ft_inherit_at_prune_vgg19_cifar100_percent_0.5_seed_2\model_best.pth.tar"

state_dict, opti_dict, start_epoch, best_prec1, cfg = resume_model(filepath3)
start_epoch, best_prec1, str(list(cfg))

=> loading checkpoint 'D:\Project\Pycharm\network-slimming\logs\ft_inherit_at_prune_vgg19_cifar100_percent_0.5_seed_2\model_best.pth.tar'
cfg: [21, 60, 'M', 107, 125, 'M', 240, 229, 201, 204, 'M', 315, 241, 141, 171, 'M', 149, 144, 165, 238]
=> loaded checkpoint 'D:\Project\Pycharm\network-slimming\logs\ft_inherit_at_prune_vgg19_cifar100_percent_0.5_seed_2\model_best.pth.tar' (epoch 151) Prec1: 0.726200


(151,
 tensor(0.7262),
 "[21, 60, 'M', 107, 125, 'M', 240, 229, 201, 204, 'M', 315, 241, 141, 171, 'M', 149, 144, 165, 238]")

In [10]:
model = vgg(dataset='cifar10', depth=19, cfg=cfg)

In [11]:
from torchstat import stat

stat(model, (3, 32, 32))

ModuleNotFoundError: No module named 'torchstat'