#### 0. 1 cuda is available

In [1]:
import torch

USE_CUDA = torch.cuda.is_available()
USE_CUDA

True

#### 0.2 pytorch version

In [2]:
import torch

torch.__version__

'1.8.1+cu102'

### 1. Pretrained VGG19 Model with Batch Normalization

In [3]:
import torchvision.models as models

model = models.vgg19_bn(pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.9.0', 'vgg19_bn', pretrained=True)

model.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): ReLU(inplace=True)
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): ReLU(inplace=True)
    (13): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (14): Conv2d(128, 256

#### 1.1 VGG19 Weight

In [4]:
model.features[1]

BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

In [5]:
model.features[1].weight.data.shape

torch.Size([64])

In [6]:
model.features[1].weight.data

tensor([ 1.5763e-07,  9.8841e-08,  2.4442e-01,  2.2678e-01,  2.4756e-01,
         5.9402e-07,  1.5344e-01,  5.5348e-01,  1.8775e-01,  4.0541e-08,
         7.3613e-08,  6.7899e-07,  1.9412e-08,  3.7765e-07, -1.5930e-07,
         4.6782e-01, -5.3255e-07,  1.8139e-02,  1.9039e-08,  2.0468e-07,
        -3.8896e-05,  8.2928e-07,  3.6763e-01, -5.7934e-08,  1.0634e-07,
         7.7692e-09, -1.2172e-07,  1.0209e-07,  1.0130e-07,  3.9670e-08,
         4.9515e-08,  6.8137e-07,  1.0767e-07,  6.3167e-08,  5.1813e-01,
         3.9662e-01,  4.0801e-06,  3.2676e-01,  3.0591e-08,  1.4233e-05,
        -4.0759e-07,  2.1676e-04,  1.8606e-06,  2.0022e-08,  6.8042e-07,
         1.0519e-06,  3.0301e-07,  1.7505e-08,  1.4339e-07,  2.6455e-08,
         3.7188e-01, -1.0622e-06,  1.9643e-01,  6.8300e-01,  1.8162e-01,
        -1.1994e-07,  3.4379e-01,  1.2878e-04,  6.3663e-01,  6.3070e-01,
         2.0438e-07,  1.0555e-08,  1.4975e-08,  3.4700e-06])

#### 1.2 VGG19 Convolution Layer

In [7]:
model.features[0]

Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [8]:
model.features[0].weight.data.shape

torch.Size([64, 3, 3, 3])

In [9]:
model.features[0].weight.data

tensor([[[[-3.2130e-08, -3.1717e-08, -6.7120e-08],
          [-2.9321e-08, -2.1596e-08, -5.3207e-08],
          [-5.3304e-08, -4.0832e-08, -6.6434e-08]],

         [[ 1.3710e-07,  1.2848e-07,  7.1270e-08],
          [ 1.5487e-07,  1.5186e-07,  8.3582e-08],
          [ 9.3392e-08,  9.9451e-08,  4.1284e-08]],

         [[ 1.7435e-07,  1.7840e-07,  1.0561e-07],
          [ 1.9644e-07,  1.9769e-07,  1.2560e-07],
          [ 1.1935e-07,  1.3447e-07,  5.9638e-08]]],


        [[[-6.3467e-08, -5.2714e-08, -3.8511e-08],
          [-1.4349e-08, -9.0426e-09, -1.7164e-08],
          [ 2.2282e-08,  1.9084e-08,  1.8150e-09]],

         [[-1.2191e-08, -6.1933e-09,  8.5022e-09],
          [ 3.8618e-08,  5.8869e-08,  2.2082e-08],
          [ 6.2501e-08,  7.0528e-08,  2.7185e-08]],

         [[ 3.0045e-08,  3.8003e-08,  3.5389e-08],
          [ 8.6743e-08,  1.1626e-07,  8.0502e-08],
          [ 7.9653e-08,  1.0057e-07,  6.7894e-08]]],


        [[[-1.3565e-01, -2.9960e-01, -1.5151e-01],
          [-2.6

### 2. Pretrained VGG19 Model without Batch Normalization

In [10]:
import torch

model = models.vgg19(pretrained=True)
# model = torch.hub.load('pytorch/vision:v0.9.0', 'vgg19', pretrained=True)
model.eval()

Using cache found in C:\Users\Administrator/.cache\torch\hub\pytorch_vision_v0.9.0


VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padd

### 2.1 features[0]: Conv2d

- 输入通道为RGB彩色图像三通道，输出通道为64，卷积核大小为3×3
- Conv2d weight：3个卷积核为一组，一共有64组卷积核，即 `model.features[0].weight.shape = [64, 3, 3, 3]`
- Conv2d bias：3个卷积核为一组，卷积核的结果相加，产生一个通道的结果。一共有64组，使用偏置对其调整，即 `model.features[0].bias.shape=[64]`

In [11]:
model.features[0]

Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [12]:
model.features[0].weight.shape

torch.Size([64, 3, 3, 3])

In [13]:
model.features[0].bias.shape

torch.Size([64])

### 2.2 features[2]: Conv2d 

- 输入通道为64，输出通道为64，卷积核大小为3×3
- Conv2d weight：64个3×3的卷积核为一组，一共有64组，即 `model.features[2].weight.shape=[64, 64, 3, 3]`
- Conv2d bias: 64个3×3的卷积核为一组，一共有64组，每一组内对应位置求和，即`model.features[2].bias.shape=[64]`

In [14]:
model.features[2]

Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [15]:
model.features[2].weight.shape

torch.Size([64, 64, 3, 3])

In [16]:
model.features[2].bias.shape

torch.Size([64])

### 2.3 Prune Conv2d Bias

In [22]:
bias = model.features[2].bias.clone()
mask = bias.gt(0.).float()
bias_mask = bias.mul(mask)
bias, mask, bias_mask

(tensor([-5.8394e-02, -1.4754e-01,  1.8017e-01, -2.8633e-01,  1.4053e-02,
         -3.9571e-02,  1.0259e-01, -8.8048e-04, -7.7598e-02, -1.8744e-01,
         -3.4763e-02,  2.2564e-02, -6.1512e-02, -3.9896e-01, -2.3920e-01,
          1.1534e-01, -1.1614e-01, -2.2889e-01, -1.6896e-01, -2.4117e-01,
          5.9063e-01,  4.4781e-04, -3.8955e-02, -8.2188e-01, -1.5366e-01,
          2.2464e-02,  4.2782e-01, -5.8604e-02, -4.8700e-02,  3.0054e-01,
         -5.6536e-02,  5.2338e-02,  2.4208e-01, -3.2136e-03,  4.8011e-01,
         -8.3752e-03,  1.7856e-01,  3.9528e-01, -2.2767e-02,  5.7821e-02,
          6.5798e-04, -1.3895e-01, -1.6600e-01,  7.9103e-03,  1.1497e-01,
          1.0045e-01,  2.3931e-01,  4.0163e-01, -1.3901e-01, -4.5015e-01,
          1.9804e-01, -1.4634e-01, -1.1509e-01,  7.2199e-02, -1.0609e-02,
          3.5647e-01,  9.0835e-02, -1.5250e-01,  2.1137e-01, -2.0729e-01,
          1.1017e-02,  2.3209e-01,  9.1408e-02,  2.5651e-02],
        grad_fn=<CloneBackward>),
 tensor([0., 0.,

### 2.4 Prune Conv2d Weight

In [26]:
weight = model.features[2].weight.clone()
num_channel = weight.shape[0]
mask = torch.randn(num_channel).gt(0.).float()
for i in range(num_channel):
    if mask[i] <= 0:
        weight[i] = torch.zeros()

torch.Size([64, 64, 3, 3])


tensor([1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
        0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 0., 0., 0., 0., 1., 0., 0., 1.])