In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(-2))

[]

In [2]:
import torchtext
from torchtext.vocab import Vectors
import torch
import numpy as np
import random

USE_CUDA = torch.cuda.is_available()
device = torch.device("cuda" if USE_CUDA else "cpu")


# 为了保证实验结果能够复现，固定随机数
SEED = 53113
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if USE_CUDA:
    torch.cuda.manual_seed(SEED)


BATCH_SIZE = 32
EMBEDDING_SIZE = 100
MAX_VOCAB_SIZE = 50000


TEXT = torchtext.data.Field(lower=True)  # 输入的内容全部小写
train, val, test = torchtext.datasets.LanguageModelingDataset.splits(
    path=".", train="text8.train.txt", validation="text8.dev.txt",
    test="text8.test.txt", text_field=TEXT
)


TEXT.build_vocab(train, max_size=MAX_VOCAB_SIZE)    # 取50000个单词
# TEXT.vocab.itos[0:10] # 其实有50002个单词，包含这两个： '<unk>'表示单词表以外的词， '<pad>'表示补全长度
# TEXT.vocab.stoi['<unk>']


# 梯度往回传的长度
train_iter, val_iter, test_iter = torchtext.data.BPTTIterator.splits(
    (train, val, test), batch_size=BATCH_SIZE, device=device,
    bptt_len=50, repeat=False, shuffle=True
)
it = iter(train_iter)  # 拿到一个 iter
for i in range(5):
    batch = next(it)  # 一个batch
    print(i)
    print(" ".join(TEXT.vocab.itos[i] for i in batch.text[:, 0].data.cpu()))
    print(" ".join(TEXT.vocab.itos[i] for i in batch.target[:, 0].data.cpu()))

D:\Program\Anaconda\envs\python37\lib\site-packages\torchtext\data\example.py:78: UserWarning: Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.', UserWarning)
D:\Program\Anaconda\envs\python37\lib\site-packages\torchtext\data\iterator.py:48: UserWarning: BPTTIterator class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)


0
anarchism originated as a term of abuse first used against early working class radicals including the diggers of the english revolution and the sans <unk> of the french revolution whilst the term is still used in a pejorative way to describe any act that used violent means to destroy the
originated as a term of abuse first used against early working class radicals including the diggers of the english revolution and the sans <unk> of the french revolution whilst the term is still used in a pejorative way to describe any act that used violent means to destroy the organization
1
organization of society it has also been taken up as a positive label by self defined anarchists the word anarchism is derived from the greek without archons ruler chief king anarchism as a political philosophy is the belief that rulers are unnecessary and should be abolished although there are differing
of society it has also been taken up as a positive label by self defined anarchists the word anarchism is der

D:\Program\Anaconda\envs\python37\lib\site-packages\torchtext\data\batch.py:23: UserWarning: Batch class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)


In [5]:
import argparse

# Training settings
parser = argparse.ArgumentParser(description='PyTorch Slimming CIFAR training')
parser.add_argument('--dataset', type=str, default='cifar100',
                    help='training dataset (default: cifar100)')
parser.add_argument('--sparsity-regularization', '-sr', dest='sr', action='store_true',
                    help='train with channel sparsity regularization')
parser.add_argument('--s', type=float, default=0.0001,
                    help='scale sparse rate (default: 0.0001)')
parser.add_argument('--refine', default='', type=str, metavar='PATH',
                    help='path to the pruned model to be fine tuned')
parser.add_argument('--batch-size', type=int, default=64, metavar='N',
                    help='input batch size for training (default: 64)')
parser.add_argument('--test-batch-size', type=int, default=256, metavar='N',
                    help='input batch size for testing (default: 256)')
parser.add_argument('--epochs', type=int, default=160, metavar='N',
                    help='number of epochs to train (default: 160)')
parser.add_argument('--start-epoch', default=0, type=int, metavar='N',
                    help='manual epoch number (useful on restarts)')
parser.add_argument('--lr', type=float, default=0.1, metavar='LR',
                    help='learning rate (default: 0.1)')
parser.add_argument('--momentum', type=float, default=0.9, metavar='M',
                    help='SGD momentum (default: 0.9)')
parser.add_argument('--weight-decay', '--wd', default=1e-4, type=float,
                    metavar='W', help='weight decay (default: 1e-4)')
parser.add_argument('--resume', default='', type=str, metavar='PATH',
                    help='path to latest checkpoint (default: none)')
parser.add_argument('--no-cuda', action='store_true', default=False,
                    help='disables CUDA training')
parser.add_argument('--seed', type=int, default=1, metavar='S',
                    help='random seed (default: 1)')
parser.add_argument('--log-interval', type=int, default=100, metavar='N',
                    help='how many batches to wait before logging training status')
parser.add_argument('--save', default='./logs', type=str, metavar='PATH',
                    help='path to save prune model (default: current directory)')
parser.add_argument('--arch', default='vgg', type=str, 
                    help='architecture to use')
parser.add_argument('--depth', default=19, type=int,
                    help='depth of the neural network')

vars(parser)

{'description': 'PyTorch Slimming CIFAR training',
 'argument_default': None,
 'prefix_chars': '-',
 'conflict_handler': 'error',
 '_registries': {'action': {None: argparse._StoreAction,
   'store': argparse._StoreAction,
   'store_const': argparse._StoreConstAction,
   'store_true': argparse._StoreTrueAction,
   'store_false': argparse._StoreFalseAction,
   'append': argparse._AppendAction,
   'append_const': argparse._AppendConstAction,
   'count': argparse._CountAction,
   'help': argparse._HelpAction,
   'version': argparse._VersionAction,
   'parsers': argparse._SubParsersAction},
  'type': {None: <function argparse.ArgumentParser.__init__.<locals>.identity(string)>}},
 '_actions': [_HelpAction(option_strings=['-h', '--help'], dest='help', nargs=0, const=None, default='==SUPPRESS==', type=None, choices=None, help='show this help message and exit', metavar=None),
  _StoreAction(option_strings=['--dataset'], dest='dataset', nargs=None, const=None, default='cifar100', type=<class 'st

In [6]:
import torch

x = torch.rand(5)

y, i = torch.sort(x)
print("x", x, "\ny", y, "\ni", i)


i.gt(2)

x tensor([0.4631, 0.1301, 0.3086, 0.1923, 0.8349]) 
y tensor([0.1301, 0.1923, 0.3086, 0.4631, 0.8349]) 
i tensor([1, 3, 2, 0, 4])


tensor([False,  True, False, False,  True])

In [13]:
import numpy as np

x = [1, 2, 3, -1, -2]
x = torch.tensor(x)
y = np.argwhere(x.data.cpu().numpy() > 0)
y

array([[0],
       [1],
       [2]], dtype=int64)

## 预训练模型

In [14]:
import torch
import torch.nn as nn
import torchvision.models as models

vgg19 = models.vgg19(pretrained=True)
vgg19

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padd

In [20]:
vgg19.features[0].weight.data

tensor([[[[-5.3474e-02, -4.9257e-02, -6.7942e-02],
          [ 1.5314e-02,  4.5068e-02,  2.1444e-03],
          [ 3.6226e-02,  1.9999e-02,  1.9864e-02]],

         [[ 1.7015e-02,  5.5403e-02, -6.2293e-03],
          [ 1.4165e-01,  2.2705e-01,  1.3758e-01],
          [ 1.2000e-01,  2.0030e-01,  9.2114e-02]],

         [[-4.4885e-02,  1.2680e-02, -1.4497e-02],
          [ 5.9742e-02,  1.3955e-01,  5.4102e-02],
          [-9.6141e-04,  5.8304e-02, -2.9663e-02]]],


        [[[ 2.6072e-01, -3.0489e-01, -5.0152e-01],
          [ 4.1376e-01, -2.0831e-01, -4.9086e-01],
          [ 5.8770e-01,  4.2851e-01, -1.3850e-01]],

         [[ 2.8746e-01, -3.3338e-01, -4.5564e-01],
          [ 3.7836e-01, -2.9144e-01, -4.9720e-01],
          [ 5.4778e-01,  4.8983e-01, -1.7166e-01]],

         [[ 6.7260e-02, -9.5386e-02, -3.8037e-02],
          [ 6.1955e-02, -1.3125e-01, -1.0691e-01],
          [ 4.8107e-02,  2.2999e-01, -3.0578e-02]]],


        [[[-3.2457e-02,  1.6281e-01,  5.9687e-02],
          [ 1.3

In [21]:
vgg19.features[0].weight.data.shape

torch.Size([64, 3, 3, 3])

In [22]:
vgg19.features[32].weight.data.shape

torch.Size([512, 512, 3, 3])

## list减法

两个list不能直接做减法，需要转成array，计算后，再转回list

In [12]:
import numpy as np

channel_origin = [64, 64, 128, 128, 256, 256, 256, 256, 512, 512, 512, 512, 512, 512, 512, 512]  # vgg19 model
channel_prune = [35, 64, 128, 128, 255, 251, 222, 180, 113, 46, 44, 34, 17, 21, 33, 80]  # prune.txt

channel_variation = np.array(channel_origin) - np.array(channel_prune)
channel_variation = list(channel_variation)

# print(len(channel_origin), len(channel_prune))
labels = ["{:>3d}-{:>3d}={:>3d}".format(origin_item, channel_prune[i], channel_variation[i]) for i, origin_item in enumerate(channel_origin)]
labels

[' 64- 35= 29',
 ' 64- 64=  0',
 '128-128=  0',
 '128-128=  0',
 '256-255=  1',
 '256-251=  5',
 '256-222= 34',
 '256-180= 76',
 '512-113=399',
 '512- 46=466',
 '512- 44=468',
 '512- 34=478',
 '512- 17=495',
 '512- 21=491',
 '512- 33=479',
 '512- 80=432']

### np.reshape()与np.resize()

- reshape 只能改变形状，不能改变原始输入包含的元素个数
- resize 可以改变尺寸,只是进行简单的裁剪和填充。如果要更加精确的使用插值，则该函数不能实现。

In [25]:
import numpy as np

x = np.random.randn(4)
x, x.shape

(array([-2.06767764, -1.1926219 ,  0.07554309, -0.0070737 ]), (4,))

In [27]:
y = x.reshape(x, (4, 1))
# y = np.reshape(4, 1)
y, x,  x.shape

(array([[-2.06767764],
        [-1.1926219 ],
        [ 0.07554309],
        [-0.0070737 ]]),
 array([-2.06767764, -1.1926219 ,  0.07554309, -0.0070737 ]),
 (4,))

In [32]:
z = np.resize(x, (4, 2))
z, z.shape, x - 1, x.shape

(array([[-2.06767764, -1.1926219 ],
        [ 0.07554309, -0.0070737 ],
        [-2.06767764, -1.1926219 ],
        [ 0.07554309, -0.0070737 ]]),
 (4, 2),
 array([[-3.06767764, -2.1926219 ],
        [-0.92445691, -1.0070737 ]]),
 (2, 2))

In [36]:
o = np.resize(z, (1,))
o, o.shape, o.size

(array([-2.06767764]), (1,), 1)

In [43]:
m = np.random.randn(1, 1)
o = np.squeeze(m)
n = np.resize(o, (1,))
m, m.shape, o, o.shape, n, n.shape

(array([[-0.7372842]]),
 (1, 1),
 array(-0.7372842),
 (),
 array([-0.7372842]),
 (1,))

### dataloader遍历

In [50]:
import torch
from torchvision import datasets, transforms

kwargs = {'num_workers': 1, 'pin_memory': True} if torch.cuda.is_available() else {}
test_loader = torch.utils.data.DataLoader(
            datasets.CIFAR10('./data.cifar10', train=False, download=True, transform=transforms.Compose([
                transforms.ToTensor(),
                transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))])),
            batch_size=256, shuffle=True, **kwargs)

Files already downloaded and verified


In [57]:
idx, data = next(enumerate(test_loader))
data[0].shape, data[1].shape

(torch.Size([256, 3, 32, 32]), torch.Size([256]))

In [58]:
import torchvision.models as models

vgg19 = models.vgg19_bn(pretrained=True)
vgg19

Downloading: "https://download.pytorch.org/models/vgg19_bn-c79401a0.pth" to C:\Users\jdema/.cache\torch\hub\checkpoints\vgg19_bn-c79401a0.pth


VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): ReLU(inplace=True)
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): ReLU(inplace=True)
    (13): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (14): Conv2d(128, 256

In [60]:
data[0][0].shape

torch.Size([3, 32, 32])

In [66]:
data1 = data[0][0].clone().unsqueeze(0)
data1.shape

torch.Size([1, 3, 32, 32])

In [70]:
value1 = vgg19.features[0](data1)
value1, value1.shape

(tensor([[[[-8.5106e-08, -7.2914e-08,  7.8384e-10,  ...,  1.6261e-06,
             2.7526e-06,  2.5523e-06],
           [-1.3694e-07, -1.5476e-07, -2.0210e-07,  ...,  2.7468e-06,
             4.3231e-06,  3.9384e-06],
           [-3.3755e-07, -4.3320e-07, -5.1764e-07,  ...,  2.9127e-06,
             4.3238e-06,  3.9556e-06],
           ...,
           [-1.5394e-06, -2.5490e-06, -2.5003e-06,  ..., -1.9278e-06,
            -1.9479e-06, -1.6941e-06],
           [-1.5366e-06, -2.6200e-06, -2.6268e-06,  ..., -1.8583e-06,
            -1.9974e-06, -1.7430e-06],
           [-1.2952e-06, -2.2182e-06, -2.2789e-06,  ..., -1.3832e-06,
            -1.6083e-06, -1.3835e-06]],
 
          [[ 8.8070e-08,  1.5682e-07,  1.6829e-07,  ...,  1.2236e-06,
             1.8164e-06,  1.5073e-06],
           [-8.1696e-08, -1.6041e-07, -2.2403e-07,  ...,  1.3481e-06,
             1.8669e-06,  1.5077e-06],
           [-4.0767e-07, -5.6811e-07, -4.2556e-07,  ...,  1.1668e-06,
             1.8114e-06,  1.5591e-06],


In [72]:
import torch.nn as nn

vgg19.eval()
for idx, m in enumerate(vgg19.features):
    data1 = m(data1)
    if isinstance(m, nn.ReLU):
        print(idx, data1.shape)
    

2 torch.Size([1, 64, 32, 32])
5 torch.Size([1, 64, 32, 32])
9 torch.Size([1, 128, 16, 16])
12 torch.Size([1, 128, 16, 16])
16 torch.Size([1, 256, 8, 8])
19 torch.Size([1, 256, 8, 8])
22 torch.Size([1, 256, 8, 8])
25 torch.Size([1, 256, 8, 8])
29 torch.Size([1, 512, 4, 4])
32 torch.Size([1, 512, 4, 4])
35 torch.Size([1, 512, 4, 4])
38 torch.Size([1, 512, 4, 4])
42 torch.Size([1, 512, 2, 2])
45 torch.Size([1, 512, 2, 2])
48 torch.Size([1, 512, 2, 2])
51 torch.Size([1, 512, 2, 2])
