### 1. list 转成 array 实现减法
两个list不能直接做减法，需要转成array，计算后，再转回list

In [14]:
import numpy as np

channel_origin = [64, 64, 128, 128, 256, 256, 256, 256, 512, 512, 512, 512, 512, 512, 512, 512]  # vgg19 model
channel_prune = [35, 64, 128, 128, 255, 251, 222, 180, 113, 46, 44, 34, 17, 21, 33, 80]  # prune.txt

channel_variation = np.array(channel_origin) - np.array(channel_prune)
channel_variation = list(channel_variation)

# print(len(channel_origin), len(channel_prune))
labels = ["{:>3d}-{:>3d}={:>3d}".format(origin_item, channel_prune[i], channel_variation[i]) for i, origin_item in enumerate(channel_origin)]
labels

[' 64- 35= 29',
 ' 64- 64=  0',
 '128-128=  0',
 '128-128=  0',
 '256-255=  1',
 '256-251=  5',
 '256-222= 34',
 '256-180= 76',
 '512-113=399',
 '512- 46=466',
 '512- 44=468',
 '512- 34=478',
 '512- 17=495',
 '512- 21=491',
 '512- 33=479',
 '512- 80=432']

### 2. np.reshape() 与 np.resize() 是不同的

- reshape 只能改变形状，不能改变原始输入包含的元素个数
- resize 可以改变尺寸,只是进行简单的裁剪和填充。如果要更加精确的使用插值，则该函数不能实现。

In [15]:
import numpy as np

x = np.random.randn(4)
x, x.shape

(array([-1.32504546,  0.0767059 , -0.19079044, -0.86248992]), (4,))

reshape

In [17]:
y = x.reshape(4, 1)
# y = np.reshape(4, 1)
y, x,  x.shape

(array([[-1.32504546],
        [ 0.0767059 ],
        [-0.19079044],
        [-0.86248992]]),
 array([-1.32504546,  0.0767059 , -0.19079044, -0.86248992]),
 (4,))

resize

In [18]:
z = np.resize(x, (4, 2))
z, z.shape, x - 1, x.shape

(array([[-1.32504546,  0.0767059 ],
        [-0.19079044, -0.86248992],
        [-1.32504546,  0.0767059 ],
        [-0.19079044, -0.86248992]]),
 (4, 2),
 array([-2.32504546, -0.9232941 , -1.19079044, -1.86248992]),
 (4,))

**size** 与 **shape** 是不一样的

In [19]:
o = np.resize(z, (1,))
o, o.shape, o.size

(array([-1.32504546]), (1,), 1)

In [20]:
m = np.random.randn(1, 1)
o = np.squeeze(m)
n = np.resize(o, (1,))
m, m.shape, o, o.shape, n, n.shape

(array([[0.99293049]]),
 (1, 1),
 array(0.99293049),
 (),
 array([0.99293049]),
 (1,))

### 3. vars() 提供打印变量的所有参数

In [22]:
import argparse

# Training settings
parser = argparse.ArgumentParser(description='PyTorch Slimming CIFAR training')
parser.add_argument('--dataset', type=str, default='cifar100',
                    help='training dataset (default: cifar100)')
parser.add_argument('--sparsity-regularization', '-sr', dest='sr', action='store_true',
                    help='train with channel sparsity regularization')
parser.add_argument('--s', type=float, default=0.0001,
                    help='scale sparse rate (default: 0.0001)')

vars(parser)

{'description': 'PyTorch Slimming CIFAR training',
 'argument_default': None,
 'prefix_chars': '-',
 'conflict_handler': 'error',
 '_registries': {'action': {None: argparse._StoreAction,
   'store': argparse._StoreAction,
   'store_const': argparse._StoreConstAction,
   'store_true': argparse._StoreTrueAction,
   'store_false': argparse._StoreFalseAction,
   'append': argparse._AppendAction,
   'append_const': argparse._AppendConstAction,
   'count': argparse._CountAction,
   'help': argparse._HelpAction,
   'version': argparse._VersionAction,
   'parsers': argparse._SubParsersAction},
  'type': {None: <function argparse.ArgumentParser.__init__.<locals>.identity(string)>}},
 '_actions': [_HelpAction(option_strings=['-h', '--help'], dest='help', nargs=0, const=None, default='==SUPPRESS==', type=None, choices=None, help='show this help message and exit', metavar=None),
  _StoreAction(option_strings=['--dataset'], dest='dataset', nargs=None, const=None, default='cifar100', type=<class 'st

### 4. gt() 大于操作，返回值为 True or False

- gt (greater than) 大于
- lt (less than) 小于
- eq (equal) 等于
- ge (greater and equal) 大于等于
- le (less and equal) 小于等于

布尔类型转换为浮点型： result.float() 返回 [1.0, 0.0, ..., 0.0]

In [ ]:
import torch

x = torch.rand(5)
y, i = torch.sort(x)
print("x", x, "\ny", y, "\ni", i)

mask = i.gt(2)
mask_float = mask.float()
mask, mask_float

### 5. np.argwhere(x > 0)  返回x中大于0的数组元组的索引

In [23]:
import numpy as np

x = [1, 2, 3, -1, -2]
x = torch.tensor(x)
y = np.argwhere(x.data.cpu().numpy() > 0)
y

array([[0],
       [1],
       [2]], dtype=int64)

### 6. squeeze() 与 unsqueeze()

- squeeze() 压缩一个维度，仅当当前维度为1，否则不做修改
- unsqueeze(num) 增加一个维度，num可以为负数，表示在倒数第num个维度增加一个维度

In [4]:
import torch

x = torch.randn(3, 1, 2)
y = x.squeeze(0)  # not modify
z = x.squeeze(1)  # modified
w = z.unsqueeze(-2)
x.shape, y.shape, z.shape, w.shape

(torch.Size([3, 1, 2]),
 torch.Size([3, 1, 2]),
 torch.Size([3, 2]),
 torch.Size([3, 1, 2]))

In [12]:
import torch
import torch.nn as nn

m = torch.nn.ReLU()
x = torch.randn(5)
y = m(x)
x, y

(tensor([-0.3862,  0.3717,  1.3680,  0.5028,  0.0278]),
 tensor([0.0000, 0.3717, 1.3680, 0.5028, 0.0278]))